"""B2 compatibility exports for the canonical position implementation."""

# BRIDGE B2 — removed in Phase 7
from position.AggregateMonsterRootScan import (
    AggregateCandidate,
    AggregateCohortReport,
    AggregateScanMemory,
    AnchoredMonsterObservation,
    Callable,
    CohortActorState,
    Mapping,
    ModuleInfo,
    Path,
    PointerPath,
    Protocol,
    ReadableRegionIndex,
    UTC,
    _CandidateSeed,
    _ReferenceScan,
    _actor_changed,
    _discover_actor_field_seeds,
    _discover_module_holder_seeds,
    _f32,
    _i32,
    _paths_for_target,
    _read_actor_state,
    _u32,
    asdict,
    bisect_left,
    dataclass,
    datetime,
    defaultdict,
    json,
    math,
    monotonic,
    re,
    replace,
    resolve_pointer_path,
    save_aggregate_report,
    scan_aggregate_monster_roots,
    scan_aligned_cohort_references,
    scan_module_rooted_paths,
    sleep,
    struct,
)
