"""B2 compatibility exports for the canonical position implementation."""

# BRIDGE B2 — removed in Phase 7
from position.AuthoritativeActorDiscovery import (
    ActiveFieldCandidate,
    AuthoritativeActorDiscovery,
    AuthoritativeActorMemory,
    AuthoritativeActorRefresh,
    Callable,
    Counter,
    HISTORICAL_PRESENCE_OFFSETS,
    Iterable,
    MemorySearchProgress,
    PresenceFieldCandidate,
    Protocol,
    RelationScanEvidence,
    SharedRelationCandidate,
    TraceTargetDiscovery,
    _active_field_candidates,
    _cancellation_requested,
    _even_sample,
    _f32,
    _has_self_alias,
    _i32,
    _pointer_like,
    _presence_field_candidates,
    _raise_if_stopped,
    _read_actor_core,
    _read_words,
    _scan_relation,
    _shared_relation_candidates,
    _strong_anchor_relation_proven,
    _target_actor_reference_count,
    _target_readable,
    _u32,
    asdict,
    dataclass,
    discover_authoritative_actors,
    math,
    refresh_authoritative_actors,
    replace,
    struct,
)
