"""B2 compatibility exports for the canonical position implementation."""

# BRIDGE B2 — removed in Phase 7
from position.NativeTraceTargets import (
    AnchoredDiscoveryEvidence,
    AnchoredDiscoveryResult,
    Callable,
    Mapping,
    ModuleInfo,
    PointerRecoveryHints,
    Protocol,
    ReadableRegionIndex,
    TraceMonsterTarget,
    TracePlayerTarget,
    TraceTargetDiscovery,
    TraceTargetEvidence,
    TraceTargetMemory,
    _aligned_pointer_offsets,
    _aligned_value_offsets,
    _f32,
    _i32,
    _module_slots_for_value,
    _monster_anchors,
    _public_monster_cohort,
    _scan_anchor_values,
    _trace_evidence,
    _u32,
    asdict,
    dataclass,
    discover_trace_targets,
    math,
    sleep,
    struct,
    trace_discovery_from_anchored,
)
