"""B2 compatibility exports for the canonical position implementation."""

# BRIDGE B2 — removed in Phase 7
from position.Win32ProcessMemory import (
    Callable,
    CtypesWin32MemoryBackend,
    ERROR_NO_MORE_FILES,
    MAX_MODULE_NAME32,
    MAX_PATH,
    MEM_COMMIT,
    MEM_PRIVATE,
    MODULEENTRY32W,
    MemoryRegion,
    MemorySearchCancelled,
    MemorySearchDeadline,
    MemorySearchDiagnostics,
    MemorySearchProgress,
    ModuleInfo,
    PAGE_GUARD,
    PAGE_NOACCESS,
    PROCESS_QUERY_INFORMATION,
    PROCESS_VM_READ,
    PositionProviderError,
    ProcessMemoryError,
    Protocol,
    TH32CS_SNAPMODULE,
    TH32CS_SNAPMODULE32,
    Win32MemoryBackend,
    Win32ProcessMemory,
    _cancellation_requested,
    _raise_if_search_stopped,
    ctypes,
    dataclass,
    monotonic,
    os,
    wintypes,
)
