"""Classify and sort every recording archive sitting directly in
recordings/ (the inbox) into recordings/training, recordings/eva_only, or
recordings/diagnostics_only, then regenerate the index.

recordings/training and recordings/eva_only are never scanned as input --
only the inbox root -- so re-running this after a previous sort is a no-op
for already-placed archives. Duplicate content (same SHA-256 as an archive
already sorted somewhere) is left in the inbox with a warning rather than
silently overwritten or duplicated.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from inventory_recordings import classify_recording  # noqa: E402

_BUCKETS = ("training", "eva_only", "diagnostics_only")


def _existing_hashes(recordings_root: Path) -> dict[str, Path]:
    hashes: dict[str, Path] = {}
    for bucket in _BUCKETS:
        bucket_dir = recordings_root / bucket
        if not bucket_dir.is_dir():
            continue
        for path in bucket_dir.glob("*.zip"):
            try:
                entry = classify_recording(path)
            except Exception:
                continue
            hashes[entry["sha256"]] = path
    return hashes


def _destination_bucket(entry: dict[str, object]) -> str:
    if entry.get("ready_for_demonstrations") or entry.get("ready_for_world_model"):
        return "training"
    if entry.get("eva_only_eligible"):
        return "eva_only"
    return "diagnostics_only"


def sort_inbox(recordings_root: Path) -> dict[str, object]:
    inbox = [path for path in sorted(recordings_root.glob("*.zip")) if path.is_file()]
    known_hashes = _existing_hashes(recordings_root)
    moved: list[dict[str, object]] = []
    skipped_duplicates: list[dict[str, object]] = []
    errors: list[dict[str, object]] = []

    for path in inbox:
        try:
            entry = classify_recording(path)
        except Exception as error:  # noqa: BLE001
            errors.append({"path": str(path), "error": f"{type(error).__name__}: {error}"})
            continue
        sha256 = entry["sha256"]
        if sha256 in known_hashes:
            skipped_duplicates.append(
                {"path": str(path), "duplicate_of": str(known_hashes[sha256])}
            )
            continue
        bucket = _destination_bucket(entry)
        destination_dir = recordings_root / bucket
        destination_dir.mkdir(parents=True, exist_ok=True)
        destination = destination_dir / path.name
        if destination.exists():
            skipped_duplicates.append(
                {"path": str(path), "duplicate_of": f"{destination} (same filename, different content)"}
            )
            continue
        shutil.move(str(path), str(destination))
        known_hashes[sha256] = destination
        moved.append({"path": str(destination), "bucket": bucket, "usable_for": entry.get("usable_for")})

    return {
        "moved": moved,
        "skipped_duplicates": skipped_duplicates,
        "errors": errors,
        "inbox_scanned": len(inbox),
    }


def _write_markdown_index(recordings_root: Path, index_json_path: Path) -> Path:
    with index_json_path.open(encoding="utf-8") as handle:
        entries = json.load(handle)
    lines = [
        "# Recording archive index",
        "",
        "Auto-generated by `devtools/archives/sort_new_recordings.py`. Do not hand-edit; it is",
        "overwritten on every run.",
        "",
        "| Archive | Bucket | Recorder | Duration (s) | Movement (retroactive) | EVA | Jump | Presence validated | Usable for |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for entry in entries:
        if "error" in entry:
            lines.append(f"| `{entry['filename']}` | | | | | | | | ERROR: {entry['error']} |")
            continue
        path = Path(entry["path"])
        bucket = path.parent.name
        duration = entry.get("duration_seconds")
        duration_text = f"{duration:.0f}" if isinstance(duration, (int, float)) else "?"
        lines.append(
            "| `{name}` | {bucket} | {recorder} | {duration} | {scheme} ({confidence:.2f}) | {eva} | {jump} | {presence} | {usable} |".format(
                name=entry["filename"],
                bucket=bucket,
                recorder=entry.get("recorder_version", "?"),
                duration=duration_text,
                scheme=entry.get("retroactive_movement_scheme", "?"),
                confidence=entry.get("retroactive_movement_confidence") or 0.0,
                eva=entry.get("eva_events", 0),
                jump=entry.get("jump_events", 0),
                presence=entry.get("presence_species_validated", False),
                usable=", ".join(entry.get("usable_for", [])),
            )
        )
    markdown_path = recordings_root / "INDEX.md"
    markdown_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return markdown_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("recordings_root", type=Path, help="e.g. recordings")
    args = parser.parse_args()

    root = args.recordings_root
    if not root.is_dir():
        raise SystemExit(f"Not a directory: {root}")

    result = sort_inbox(root)
    print(json.dumps(result, indent=2))

    entries = []
    for bucket in _BUCKETS:
        bucket_dir = root / bucket
        if not bucket_dir.is_dir():
            continue
        for path in sorted(bucket_dir.glob("*.zip")):
            try:
                entries.append(classify_recording(path))
            except Exception as error:  # noqa: BLE001
                entries.append({"path": str(path), "filename": path.name, "error": f"{type(error).__name__}: {error}"})

    index_json_path = root / "INDEX.json"
    index_json_path.write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")
    markdown_path = _write_markdown_index(root, index_json_path)
    print(f"\nIndex regenerated: {index_json_path}", file=sys.stderr)
    print(f"Index regenerated: {markdown_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
