"""Read-only development-facing artifact inventory.

Not a database -- a thin reader/normalizer over the already-existing
tracked/frozen inventories: ``recordings/INDEX.json``,
``recording_provenance.json``, ``docs/migration/CHECKPOINT_INVENTORY.tsv``,
and ``docs/migration/ARTIFACT_MANIFEST.tsv``. Every function here only
reads; none of them write, evaluate a model, select a policy, or modify
any inventory/metadata file. Frozen migration evidence
(``CHECKPOINT_INVENTORY.tsv``/``ARTIFACT_MANIFEST.tsv``) is presented
exactly as recorded, including its pre-Phase-7-collapse path strings --
this module never rewrites or "corrects" those paths, since they are
Phase-1/Phase-2 frozen evidence.
"""

from __future__ import annotations

import csv
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]


@dataclass(frozen=True, slots=True)
class RecordingEntry:
    filename: str
    sha256: str
    recorder_version: str
    duration_seconds: float
    total_frames: int
    retroactive_movement_scheme: str | None
    ready_for_world_model: bool
    eva_only_eligible: bool
    usable_for: tuple[str, ...]
    provenance_role: str | None
    provenance_note: str | None


@dataclass(frozen=True, slots=True)
class CheckpointEntry:
    path: str
    size_bytes: int
    sha256: str
    policy_class_module: str
    policy_class_qualname: str
    farming_contract_metadata_version: str
    obs_space_shape: str
    action_space_spec: str
    loadable_under_current_source: str


def list_recordings(repo: Path = REPO) -> list[RecordingEntry]:
    """Reads recordings/INDEX.json (as-generated by
    devtools/archives/sort_new_recordings.py) joined with
    recording_provenance.json's legacy-attestation notes, where present.
    Returns [] if either file is absent -- never raises for a missing
    inventory, since the inventory itself is optional local state."""
    index_path = repo / "recordings" / "INDEX.json"
    if not index_path.is_file():
        return []
    entries = json.loads(index_path.read_text(encoding="utf-8"))

    provenance: dict[str, dict[str, Any]] = {}
    provenance_path = repo / "recording_provenance.json"
    if provenance_path.is_file():
        provenance = json.loads(provenance_path.read_text(encoding="utf-8")).get("recordings", {})

    results: list[RecordingEntry] = []
    for row in entries:
        sha = str(row.get("sha256", ""))
        prov = provenance.get(sha, {})
        results.append(
            RecordingEntry(
                filename=str(row.get("filename", "")),
                sha256=sha,
                recorder_version=str(row.get("recorder_version", "")),
                duration_seconds=float(row.get("duration_seconds", 0.0)),
                total_frames=int(row.get("total_frames", 0)),
                retroactive_movement_scheme=row.get("retroactive_movement_scheme"),
                ready_for_world_model=bool(row.get("ready_for_world_model", False)),
                eva_only_eligible=bool(row.get("eva_only_eligible", False)),
                usable_for=tuple(row.get("usable_for", ())),
                provenance_role=prov.get("recording_role"),
                provenance_note=prov.get("note"),
            )
        )
    return results


def list_checkpoints(repo: Path = REPO) -> list[CheckpointEntry]:
    """Reads docs/migration/CHECKPOINT_INVENTORY.tsv exactly as frozen --
    including its pre-Phase-7-collapse path strings, never translated or
    rewritten here. This is Phase-2 frozen evidence; this function is a
    read-only view over it, not a second copy."""
    inventory_path = repo / "docs" / "migration" / "CHECKPOINT_INVENTORY.tsv"
    if not inventory_path.is_file():
        return []
    with inventory_path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))
    return [
        CheckpointEntry(
            path=row["path"],
            size_bytes=int(row["size_bytes"]),
            sha256=row["sha256"],
            policy_class_module=row["policy_class_module"],
            policy_class_qualname=row["policy_class_qualname"],
            farming_contract_metadata_version=row["farming_contract_metadata_version"],
            obs_space_shape=row["obs_space_shape"],
            action_space_spec=row["action_space_spec"],
            loadable_under_current_source=row["loadable_under_current_source"],
        )
        for row in rows
    ]


def summarize(repo: Path = REPO) -> dict[str, Any]:
    """A small, dependency-free summary suitable for a GUI panel or CLI
    printout -- counts only, no per-row detail, so this stays cheap even
    against the full 313-checkpoint inventory."""
    recordings = list_recordings(repo)
    checkpoints = list_checkpoints(repo)
    return {
        "recording_count": len(recordings),
        "recordings_ready_for_world_model": sum(1 for r in recordings if r.ready_for_world_model),
        "recordings_eva_only_eligible": sum(1 for r in recordings if r.eva_only_eligible),
        "checkpoint_count": len(checkpoints),
        "checkpoints_loadable_under_current_source": sum(
            1 for c in checkpoints if c.loadable_under_current_source.startswith("yes")
        ),
    }
