"""2026-08-15: development-pool validation of `select_persistent_waypoint_
experimental_invalid_hop_guard` ("v2" / "D"), per explicit user
instruction, BEFORE any fresh (840M) qualification pool. 830M/812M/640M/
663M/26-fixtures are all development data at this point (already
inspected), so used aggressively here -- this script's own results are
not held out for a future qualification claim.

Compares exactly two systems, no trained PPO:
  A = frozen 0051200 + qualified three-tier selector (production default,
      restored 2026-08-15 after v1 failed qualification)
  D = frozen 0051200 + select_persistent_waypoint_experimental_invalid_
      hop_guard ("v2": only substitutes when the qualified selector's own
      any_fallback target is itself _segment_clear=False)

For 830M and 812M, A's cached results (generated by this exact SAME
qualified-selector code, before any patch existed) are reused rather than
rerun, to avoid ~360 redundant episodes of compute:
  - 830M obstacle A: evaluations/router_patch_qualification_compare_
    result.json ("A_baseline_old_selector")
  - 812M obstacle A: evaluations/router_mix_dev_pool_baseline_eval_
    pre_selector_patch.json
830M's own 40 open episodes were NEVER evaluated under any condition
before (the earlier 830M report's "open" leg reused the unrelated 777M
pool by mistake -- MISTAKES.md, 2026-08-15) -- both A and D are run fresh
here against the manifest's actual open stratum.

640M/663M/26-fixtures: A's cached pre-v1-patch results are reused
(evaluations/general_router_bridge_check_corrected_previous_steering.json,
evaluations/beginner_routing_two_wall_s_route_eval_corrected_previous_
steering.json, evaluations/routing_regression_fixtures_result_pre_
selector_patch.json); D is run fresh against the identical seeds/specs.

Predeclared development gate (verbatim from user instruction):
  On 830M: D's collision set must be a STRICT subset of A's, D introduces
    ZERO new collision episodes, D success >= A success.
  On historical/dev pools (812M, 640M, 663M, 26 fixtures): no new
    collision episode relative to the qualified selector (subset, not
    necessarily strict).
  Planner failures: no increase anywhere.
If even one new collision appears anywhere, STOP -- do not start
adjusting ranking again; treat it as evidence the abstraction itself
needs rethinking, not a tuning target.

No selector code is modified by this script. No training. 840M is not
created and 820M is not touched regardless of outcome -- per explicit
instruction, that decision is made in a SEPARATE step after this gate's
result is reported and reviewed.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from stable_baselines3 import PPO

import scratchpad_general_router_episode as gre
from scratchpad_beginner_navigation_mix_pools import DEV_POOL_SPEC_SEED, eval_obstacle_manifest, load_manifest
from scratchpad_beginner_routing_randomized_walls import N_EVAL_PER_SIDE, SUITE_SPEC_SEED as BRIDGE_640M_SEED, held_out_randomized_wall_specs_for_side
from scratchpad_beginner_routing_two_wall_s_route import (
    N_EVAL_PER_DIRECTION, S_ROUTE_DIRECTIONS, SUITE_SPEC_SEED as TWOWALL_663M_SEED, held_out_two_wall_specs_for_direction,
)
from scratchpad_general_router_episode import build_multi_wall_world, run_episode_general_router, summarize_general_router
from scratchpad_router_patch_qualification_pool import QUALIFICATION_SPEC_SEED
from scratchpad_routing_regression_fixtures import FIXTURES, SINGLE_WALL_640M, SINGLE_WALL_705M, TWO_WALL_663M, TWO_WALL_706M, _spec_and_world
from simulator.kinodynamic_route_planner import select_persistent_waypoint_experimental_invalid_hop_guard
from simulator.navigation_history import NavigationHistoryWrapper
from simulator.single_obstacle_env import GAP_SIDES, MAP_HALF_SIZE_CELLS
from simulator.static_waypoint_env import FIXED_HEADING, StaticWaypointWrapper, WaypointSpec, make_static_waypoint_env

ROOT = Path(__file__).resolve().parents[1]
BASELINE_CHECKPOINT = ROOT / "models" / "generalized_waypoint_both_seed2_0051200.zip"
DEV_POOL_EPISODE_SEED_BASE = 812_600_000  # matches audit scripts' canonical base
QUAL_POOL_EPISODE_SEED_BASE = 830_600_000
OPEN_EPISODE_STEPS = 100
BRIDGE_EPISODE_SEED_BASE = 925_000_000
TWOWALL_EPISODE_SEED_BASE = 935_000_000


def eval_open_stratum(model, manifest: dict, *, episode_seed_base: int) -> dict:
    """Evaluates a manifest's OWN "open" stratum (never done before for
    830M -- MISTAKES.md 2026-08-15). Mirrors eval_held_out's per-episode
    loop exactly, but reconstructs WaypointSpec from the manifest's stored
    fields instead of drawing from a different pool.

    `episode_outcomes` (2026-08-15, per explicit user instruction for the
    820M final rule "D per-episode outcomes identical to A"): the ordered
    per-episode outcome list, not just aggregate counts, so two calls can
    be compared for EXACT identity, not merely equal totals."""
    successes = collisions = timeouts = 0
    episode_outcomes: list[str] = []
    for i, ep in enumerate(manifest["strata"]["open"]["accepted"]):
        spec = WaypointSpec(heading=ep["heading"], bearing=ep["bearing"], distance=ep["distance"], position_offset=tuple(ep["position_offset"]))
        seed = episode_seed_base + i
        raw_env = make_static_waypoint_env(episode_steps=OPEN_EPISODE_STEPS, seed=seed)
        env = StaticWaypointWrapper(NavigationHistoryWrapper(raw_env), spec_source=lambda spec=spec: spec)
        obs, _info = env.reset(seed=seed)
        outcome = "timeout"
        for _tick in range(OPEN_EPISODE_STEPS):
            action, _state = model.predict(obs, deterministic=True)
            obs, reward, term, trunc, info = env.step(action)
            if term:
                if reward >= 1.0:
                    successes += 1
                    outcome = "success"
                elif reward <= -1.0:
                    collisions += 1
                    outcome = "collision"
                break
            if trunc:
                timeouts += 1
                outcome = "timeout"
                break
        else:
            timeouts += 1
        episode_outcomes.append(outcome)
        env.close()
    n = len(manifest["strata"]["open"]["accepted"])
    return {"n": n, "successes": successes, "collisions": collisions, "timeouts": timeouts, "episode_outcomes": episode_outcomes,
            "success_rate": successes / n, "collision_rate": collisions / n}


def eval_obstacle_guarded(model, manifest: dict, *, episode_seed_base: int) -> dict:
    original = gre.select_persistent_waypoint
    gre.select_persistent_waypoint = select_persistent_waypoint_experimental_invalid_hop_guard
    try:
        return eval_obstacle_manifest(model, manifest, episode_seed_base=episode_seed_base)
    finally:
        gre.select_persistent_waypoint = original


def eval_bridge_640m_guarded(model) -> dict:
    original = gre.select_persistent_waypoint
    gre.select_persistent_waypoint = select_persistent_waypoint_experimental_invalid_hop_guard
    try:
        import math
        output = {}
        for side in GAP_SIDES:
            specs = held_out_randomized_wall_specs_for_side(N_EVAL_PER_SIDE, gap_side=side, seed=BRIDGE_640M_SEED)
            results = []
            for i, spec in enumerate(specs):
                obstacle = spec.obstacle
                map_model, world = build_multi_wall_world([obstacle])
                cell_size = map_model.native_units_per_cell
                center = MAP_HALF_SIZE_CELLS
                start_native = map_model.layout_to_native(center, center)
                final_native = (
                    start_native[0] + math.cos(FIXED_HEADING) * obstacle.distance_cells * cell_size,
                    start_native[1] + math.sin(FIXED_HEADING) * obstacle.distance_cells * cell_size,
                )
                initial_heading = FIXED_HEADING + spec.approach_heading_offset_radians
                result = run_episode_general_router(
                    model, map_model, world, initial_heading=initial_heading, final_native=final_native,
                    seed=BRIDGE_EPISODE_SEED_BASE + i, use_persistence_controller=False,
                )
                results.append(result)
            output[side] = {"summary": summarize_general_router(results), "episodes": [r.__dict__ for r in results]}
        return output
    finally:
        gre.select_persistent_waypoint = original


def eval_twowall_663m_guarded(model) -> dict:
    original = gre.select_persistent_waypoint
    gre.select_persistent_waypoint = select_persistent_waypoint_experimental_invalid_hop_guard
    try:
        import math
        output = {}
        for direction in S_ROUTE_DIRECTIONS:
            specs = held_out_two_wall_specs_for_direction(N_EVAL_PER_DIRECTION, direction=direction, seed=TWOWALL_663M_SEED)
            results = []
            for i, spec in enumerate(specs):
                wall1, wall2 = spec.wall1_obstacle_spec(), spec.wall2_obstacle_spec()
                map_model, world = build_multi_wall_world([wall1, wall2])
                cell_size = map_model.native_units_per_cell
                center = MAP_HALF_SIZE_CELLS
                start_native = map_model.layout_to_native(center, center)
                final_native = (
                    start_native[0] + math.cos(FIXED_HEADING) * spec.distance_cells * cell_size,
                    start_native[1] + math.sin(FIXED_HEADING) * spec.distance_cells * cell_size,
                )
                initial_heading = FIXED_HEADING + spec.approach_heading_offset_radians
                result = run_episode_general_router(
                    model, map_model, world, initial_heading=initial_heading, final_native=final_native,
                    seed=TWOWALL_EPISODE_SEED_BASE + i, use_persistence_controller=False,
                )
                results.append(result)
            output[direction] = {"summary": summarize_general_router(results), "episodes": [r.__dict__ for r in results]}
        return output
    finally:
        gre.select_persistent_waypoint = original


def eval_fixtures_guarded(model) -> list[dict]:
    # Matches scratchpad_routing_regression_fixtures.py's own main()
    # exactly (that dict is a local variable there, not importable).
    seed_base_map = {
        SINGLE_WALL_640M: 925_000_000, TWO_WALL_663M: 935_000_000,
        SINGLE_WALL_705M: 940_000_000, TWO_WALL_706M: 950_000_000,
    }
    original = gre.select_persistent_waypoint
    gre.select_persistent_waypoint = select_persistent_waypoint_experimental_invalid_hop_guard
    try:
        results = []
        for fx in FIXTURES:
            map_model, world, initial_heading, final_native = _spec_and_world(fx)
            episode_seed = seed_base_map[fx.spec_seed] + fx.index
            result_b = run_episode_general_router(model, map_model, world, initial_heading=initial_heading, final_native=final_native, seed=episode_seed, use_persistence_controller=True)
            results.append({"name": fx.name, "outcome_d_with_controller": result_b.outcome})
        return results
    finally:
        gre.select_persistent_waypoint = original


def main() -> None:
    model = PPO.load(str(BASELINE_CHECKPOINT), device="cpu")
    report: dict = {}

    # -- 830M --
    print(f"\n{'=' * 90}\n830M obstacle: D (guarded) vs cached A\n{'=' * 90}")
    qual_manifest = load_manifest(ROOT / "evaluations" / f"router_mix_qualification_pool_{QUALIFICATION_SPEC_SEED}_manifest.json")
    a_830_cached = json.loads((ROOT / "evaluations" / "router_patch_qualification_compare_result.json").read_text(encoding="utf-8"))
    a_830_obstacle = a_830_cached["results"]["A_baseline_old_selector"]["obstacle"]
    d_830_obstacle = eval_obstacle_guarded(model, qual_manifest, episode_seed_base=QUAL_POOL_EPISODE_SEED_BASE)
    print(f"  A (cached): n={a_830_obstacle['n_total']} collisions={a_830_obstacle['collision_episode_keys']}")
    print(f"  D (fresh):  n={d_830_obstacle['n_total']} collisions={d_830_obstacle['collision_episode_keys']}")
    report["830M_obstacle"] = {"A": a_830_obstacle, "D": d_830_obstacle}

    print(f"\n830M open (actual manifest stratum, fixing the earlier eval_held_out mismatch):")
    a_830_open = eval_open_stratum(model, qual_manifest, episode_seed_base=830_700_000)
    d_830_open = eval_open_stratum(model, qual_manifest, episode_seed_base=830_700_000)  # D uses guard, but selector isn't invoked for open episodes at all
    print(f"  A: {a_830_open}")
    print(f"  D: {d_830_open}")
    report["830M_open"] = {"A": a_830_open, "D": d_830_open}

    # -- 812M --
    print(f"\n{'=' * 90}\n812M obstacle: D (guarded) vs cached A\n{'=' * 90}")
    dev_manifest = load_manifest(ROOT / "evaluations" / f"router_mix_dev_pool_{DEV_POOL_SPEC_SEED}_manifest.json")
    a_812 = json.loads((ROOT / "evaluations" / "router_mix_dev_pool_baseline_eval_pre_selector_patch.json").read_text(encoding="utf-8"))
    d_812 = eval_obstacle_guarded(model, dev_manifest, episode_seed_base=DEV_POOL_EPISODE_SEED_BASE)
    print(f"  A (cached): n={a_812['n_total']} collisions={a_812['collision_episode_keys']}")
    print(f"  D (fresh):  n={d_812['n_total']} collisions={d_812['collision_episode_keys']}")
    report["812M"] = {"A": a_812, "D": d_812}

    # -- 640M bridge check --
    print(f"\n{'=' * 90}\n640M bridge check: D (guarded) vs cached A\n{'=' * 90}")
    a_640 = json.loads((ROOT / "evaluations" / "general_router_bridge_check_corrected_previous_steering.json").read_text(encoding="utf-8"))
    d_640 = eval_bridge_640m_guarded(model)
    a_640_collisions = sorted((side, i) for side in GAP_SIDES for i, e in enumerate(a_640[side]["episodes"]) if e["outcome"] == "collision")
    d_640_collisions = sorted((side, i) for side in GAP_SIDES for i, e in enumerate(d_640[side]["episodes"]) if e["outcome"] == "collision")
    print(f"  A collisions: {a_640_collisions}")
    print(f"  D collisions: {d_640_collisions}")
    report["640M"] = {"A_collisions": [str(c) for c in a_640_collisions], "D_collisions": [str(c) for c in d_640_collisions], "D_full": d_640}

    # -- 663M two-wall --
    print(f"\n{'=' * 90}\n663M two-wall S-route: D (guarded) vs cached A\n{'=' * 90}")
    a_663 = json.loads((ROOT / "evaluations" / "beginner_routing_two_wall_s_route_eval_corrected_previous_steering.json").read_text(encoding="utf-8"))
    d_663 = eval_twowall_663m_guarded(model)
    a_663_collisions = sorted((d, i) for d in S_ROUTE_DIRECTIONS for i, e in enumerate(a_663[d]["episodes"]) if e["outcome"] == "collision")
    d_663_collisions = sorted((d, i) for d in S_ROUTE_DIRECTIONS for i, e in enumerate(d_663[d]["episodes"]) if e["outcome"] == "collision")
    print(f"  A collisions: {a_663_collisions}")
    print(f"  D collisions: {d_663_collisions}")
    report["663M"] = {"A_collisions": [str(c) for c in a_663_collisions], "D_collisions": [str(c) for c in d_663_collisions], "D_full": d_663}

    # -- 26 fixtures --
    print(f"\n{'=' * 90}\n26 fixtures: D (guarded, with controller) vs cached A (qualified, with controller)\n{'=' * 90}")
    a_fixtures = json.loads((ROOT / "evaluations" / "routing_regression_fixtures_result_pre_selector_patch.json").read_text(encoding="utf-8"))
    a_fixtures_by_name = {r["name"]: r for r in a_fixtures["results"]}
    d_fixtures = eval_fixtures_guarded(model)
    a_fixture_collisions = sorted(name for name, r in a_fixtures_by_name.items() if r["actual_b"] == "collision")
    d_fixture_collisions = sorted(r["name"] for r in d_fixtures if r["outcome_d_with_controller"] == "collision")
    print(f"  A collisions (condition B = qualified+controller): {a_fixture_collisions}")
    print(f"  D collisions (guarded+controller):                 {d_fixture_collisions}")
    report["26_fixtures"] = {"A_collisions": a_fixture_collisions, "D_collisions": d_fixture_collisions, "D_full": d_fixtures}

    gate = compute_gate(
        a_830_obstacle=a_830_obstacle, d_830_obstacle=d_830_obstacle, a_812=a_812, d_812=d_812,
        a_640=a_640, d_640=d_640, a_663=a_663, d_663=d_663,
        a_fixtures_by_name=a_fixtures_by_name, d_fixtures=d_fixtures,
    )
    report["gate"] = gate
    out_path = ROOT / "evaluations" / "router_v2_guarded_development_validation.json"
    out_path.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
    print(f"\nSaved to {out_path}")


def compute_gate(
    *, a_830_obstacle: dict, d_830_obstacle: dict, a_812: dict, d_812: dict,
    a_640: dict, d_640: dict, a_663: dict, d_663: dict,
    a_fixtures_by_name: dict, d_fixtures: list[dict],
) -> dict:
    """2026-08-15: the mechanical gate, including the PLANNER-FAILURE
    checks that were predeclared in this module's own docstring
    ("Planner failures: no increase anywhere") but were missing from the
    first version's `overall_pass` -- a real procedural omission, user-
    caught. Callable against either freshly-computed pieces (from main())
    or pieces reloaded from already-saved artifacts (see scratchpad_
    router_v2_recompute_gate_from_artifact.py) -- identical logic either
    way, so a fresh run and an artifact-only recompute can never silently
    diverge."""
    print(f"\n{'=' * 90}\nPREDECLARED DEVELOPMENT GATE\n{'=' * 90}")

    a_830_set = set(a_830_obstacle["collision_episode_keys"])
    d_830_set = set(d_830_obstacle["collision_episode_keys"])
    d_830_success = round(d_830_obstacle["combined_summary"]["success_rate"] * d_830_obstacle["n_total"])
    a_830_success = round(a_830_obstacle["combined_summary"]["success_rate"] * a_830_obstacle["n_total"])
    gate_830_strict_subset = d_830_set < a_830_set
    gate_830_no_new = d_830_set.issubset(a_830_set)
    gate_830_success = d_830_success >= a_830_success
    a_830_pf = round(a_830_obstacle["combined_summary"]["planner_failure_rate"] * a_830_obstacle["n_total"])
    d_830_pf = round(d_830_obstacle["combined_summary"]["planner_failure_rate"] * d_830_obstacle["n_total"])
    gate_830_planner = d_830_pf <= a_830_pf
    gate_830 = gate_830_strict_subset and gate_830_no_new and gate_830_success and gate_830_planner
    print(f"830M: A_collisions={sorted(a_830_set)} D_collisions={sorted(d_830_set)} "
          f"A_success={a_830_success} D_success={d_830_success} A_planner_fail={a_830_pf} D_planner_fail={d_830_pf}")
    print(f"  strict_subset={gate_830_strict_subset} no_new={gate_830_no_new} success_ge_a={gate_830_success} "
          f"planner_no_increase={gate_830_planner} -> PASS={gate_830}")

    a_812_set, d_812_set = set(a_812["collision_episode_keys"]), set(d_812["collision_episode_keys"])
    a_812_pf = round(a_812["combined_summary"]["planner_failure_rate"] * a_812["n_total"])
    d_812_pf = round(d_812["combined_summary"]["planner_failure_rate"] * d_812["n_total"])
    gate_812_collisions = d_812_set.issubset(a_812_set)
    gate_812_planner = d_812_pf <= a_812_pf
    gate_812 = gate_812_collisions and gate_812_planner
    print(f"812M: A_collisions={sorted(a_812_set)} D_collisions={sorted(d_812_set)} "
          f"A_planner_fail={a_812_pf} D_planner_fail={d_812_pf} -> no_new={gate_812_collisions} planner_ok={gate_812_planner}")

    a_640_collisions = sorted((side, i) for side in GAP_SIDES for i, e in enumerate(a_640[side]["episodes"]) if e["outcome"] == "collision")
    d_640_collisions = sorted((side, i) for side in GAP_SIDES for i, e in enumerate(d_640[side]["episodes"]) if e["outcome"] == "collision")
    a_640_pf = set((side, i) for side in GAP_SIDES for i, e in enumerate(a_640[side]["episodes"]) if e["outcome"] == "planner_failure_no_route_found")
    d_640_pf = set((side, i) for side in GAP_SIDES for i, e in enumerate(d_640[side]["episodes"]) if e["outcome"] == "planner_failure_no_route_found")
    gate_640_collisions = set(d_640_collisions).issubset(set(a_640_collisions))
    gate_640_planner = d_640_pf.issubset(a_640_pf)
    gate_640 = gate_640_collisions and gate_640_planner
    print(f"640M: A_collisions={a_640_collisions} D_collisions={d_640_collisions} -> no_new={gate_640_collisions}")
    print(f"      A_planner_fail={sorted(a_640_pf)} D_planner_fail={sorted(d_640_pf)} -> planner_ok={gate_640_planner} (equal={a_640_pf == d_640_pf})")

    a_663_collisions = sorted((d, i) for d in S_ROUTE_DIRECTIONS for i, e in enumerate(a_663[d]["episodes"]) if e["outcome"] == "collision")
    d_663_collisions = sorted((d, i) for d in S_ROUTE_DIRECTIONS for i, e in enumerate(d_663[d]["episodes"]) if e["outcome"] == "collision")
    a_663_pf = set((d, i) for d in S_ROUTE_DIRECTIONS for i, e in enumerate(a_663[d]["episodes"]) if e["outcome"] == "planner_failure_no_route_found")
    d_663_pf = set((d, i) for d in S_ROUTE_DIRECTIONS for i, e in enumerate(d_663[d]["episodes"]) if e["outcome"] == "planner_failure_no_route_found")
    gate_663_collisions = set(d_663_collisions).issubset(set(a_663_collisions))
    gate_663_planner = d_663_pf.issubset(a_663_pf)
    gate_663 = gate_663_collisions and gate_663_planner
    print(f"663M: A_collisions={a_663_collisions} D_collisions={d_663_collisions} -> no_new={gate_663_collisions}")
    print(f"      A_planner_fail={sorted(a_663_pf)} D_planner_fail={sorted(d_663_pf)} -> planner_ok={gate_663_planner} (equal={a_663_pf == d_663_pf})")

    a_fixture_collisions = sorted(name for name, r in a_fixtures_by_name.items() if r["actual_b"] == "collision")
    d_fixture_collisions = sorted(r["name"] for r in d_fixtures if r["outcome_d_with_controller"] == "collision")
    a_fixtures_pf = set(name for name, r in a_fixtures_by_name.items() if r["actual_b"] == "planner_failure_no_route_found")
    d_fixtures_pf = set(r["name"] for r in d_fixtures if r["outcome_d_with_controller"] == "planner_failure_no_route_found")
    gate_fixtures_collisions = set(d_fixture_collisions).issubset(set(a_fixture_collisions))
    gate_fixtures_planner = d_fixtures_pf.issubset(a_fixtures_pf)
    gate_fixtures = gate_fixtures_collisions and gate_fixtures_planner
    print(f"26fixtures: A_collisions={a_fixture_collisions} D_collisions={d_fixture_collisions} -> no_new={gate_fixtures_collisions}")
    print(f"            A_planner_fail={sorted(a_fixtures_pf)} D_planner_fail={sorted(d_fixtures_pf)} -> planner_ok={gate_fixtures_planner} (equal={a_fixtures_pf == d_fixtures_pf})")

    overall_pass = gate_830 and gate_812 and gate_640 and gate_663 and gate_fixtures
    print(f"\n{'=' * 90}\nOVERALL DEVELOPMENT GATE (including planner-failure checks): {'PASS' if overall_pass else 'FAIL'}\n{'=' * 90}")
    if not overall_pass:
        print("At least one pool shows a new collision, a new planner failure, or the strict-830M-improvement condition failed.")
        print("Per instruction: do NOT start adjusting ranking again -- report and reconsider the abstraction.")

    return {
        "gate_830_strict_subset": gate_830_strict_subset, "gate_830_no_new_collisions": gate_830_no_new,
        "gate_830_success": gate_830_success, "gate_830_planner_no_increase": gate_830_planner, "gate_830_pass": gate_830,
        "gate_812_no_new_collisions": gate_812_collisions, "gate_812_planner_no_increase": gate_812_planner, "gate_812_pass": gate_812,
        "gate_640_no_new_collisions": gate_640_collisions, "gate_640_planner_subset": gate_640_planner, "gate_640_pass": gate_640,
        "gate_663_no_new_collisions": gate_663_collisions, "gate_663_planner_subset": gate_663_planner, "gate_663_pass": gate_663,
        "gate_fixtures_no_new_collisions": gate_fixtures_collisions, "gate_fixtures_planner_subset": gate_fixtures_planner, "gate_fixtures_pass": gate_fixtures,
        "overall_pass": overall_pass,
    }


if __name__ == "__main__":
    main()
